### ISSUE TITLE
Bugs with Unity Update

### ISSUE THREAD

**Issue by LiamVallance** [Hodge0699/McompProject#88]
Due to a security issue with the Unity version we were using we had to update to a slightly newer version.
Below are the known Bugs cause by the update:

- Left and right room walls no longer collide with the player allowing the player to pass through and out of the map

**Comment by 14016036** [comment]
seems to be an issue with the spawning of the side walls, when duping the walls during run time and moving them slightly in the player is unable to pass through them. 

@JakeP121 did the room spawning so it'd probably be quicker for Jake to figure out why this is an issue compared to the rest of us.

**Comment by JakeP121** [comment]
I've had a look at this and I don't think it's anything to do with the room spawning since the rest of the walls still work fine.

I assume its something physics related but moving the move function into FixedUpdate() in PlayerInputManager and trying different methods of moving the player like rigidbody.MovePosition, rigidbody.AddForce and transform.Translate seem to do nothing.

**Comment by JakeP121** [comment]
Fixed this. There was a problem with the rigidbody-to-rigidbody collision for the player and side walls (or the northern most side wall when they were split by a door). This must be a bug in the new Unity update since it only happens sometimes. I've removed the rigidbody from the Cube prefab so it'll use rigidbody-to-collider collisions when interacting with the player's rigidbody. I also had to add a rigidbody to the bullet to allow them to collide with the new non-rigidbody walls.
